/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package salesTrackerPackage;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;

/**
 *
 * @author ronjoshual.bersabal
 */
public class dateRange extends javax.swing.JDialog {

    /**
     * Creates new form dateRange
     */
    private String startDate, endDate;
    
    public dateRange(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        dateChooserPanelBeanInfo1 = new com.toedter.calendar.demo.DateChooserPanelBeanInfo();
        jCalendarDemo1 = new com.toedter.calendar.demo.JCalendarDemo();
        optionPanel = new javax.swing.JPanel();
        optionDay = new javax.swing.JPanel();
        todayLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        optionWeek = new javax.swing.JPanel();
        weekLabel = new javax.swing.JLabel();
        optionMonth = new javax.swing.JPanel();
        monthLabel = new javax.swing.JLabel();
        optionCustom = new javax.swing.JPanel();
        customLabel = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        todayPanel = new javax.swing.JPanel();
        dayChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dayButton = new javax.swing.JButton();
        weekPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        weekChooser = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();
        dateRange = new javax.swing.JLabel();
        setWeekDateButton = new javax.swing.JButton();
        monthPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        monthChooser = new com.toedter.calendar.JMonthChooser();
        setMonthButton = new javax.swing.JButton();
        yearChooser = new com.toedter.calendar.JYearChooser();
        jLabel4 = new javax.swing.JLabel();
        monthDateRange = new javax.swing.JLabel();
        customPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        startCalendar = new com.toedter.calendar.JCalendar();
        endCalendar = new com.toedter.calendar.JCalendar();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        setCustomButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        customDateRange = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jCalendarDemo1Layout = new javax.swing.GroupLayout(jCalendarDemo1.getContentPane());
        jCalendarDemo1.getContentPane().setLayout(jCalendarDemo1Layout);
        jCalendarDemo1Layout.setHorizontalGroup(
            jCalendarDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jCalendarDemo1Layout.setVerticalGroup(
            jCalendarDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        optionPanel.setBackground(new java.awt.Color(255, 255, 255));

        optionDay.setBackground(new java.awt.Color(240, 240, 240));
        optionDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionDayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionDayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionDayMouseExited(evt);
            }
        });

        todayLabel.setText("Select Day");

        javax.swing.GroupLayout optionDayLayout = new javax.swing.GroupLayout(optionDay);
        optionDay.setLayout(optionDayLayout);
        optionDayLayout.setHorizontalGroup(
            optionDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionDayLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(todayLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionDayLayout.setVerticalGroup(
            optionDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionDayLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(todayLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Custom Date Selection");

        optionWeek.setBackground(new java.awt.Color(240, 240, 240));
        optionWeek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionWeekMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionWeekMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionWeekMouseExited(evt);
            }
        });

        weekLabel.setText("Select Week");

        javax.swing.GroupLayout optionWeekLayout = new javax.swing.GroupLayout(optionWeek);
        optionWeek.setLayout(optionWeekLayout);
        optionWeekLayout.setHorizontalGroup(
            optionWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionWeekLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(weekLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionWeekLayout.setVerticalGroup(
            optionWeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionWeekLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(weekLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        optionMonth.setBackground(new java.awt.Color(240, 240, 240));
        optionMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionMonthMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionMonthMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionMonthMouseExited(evt);
            }
        });

        monthLabel.setText("Select Month");

        javax.swing.GroupLayout optionMonthLayout = new javax.swing.GroupLayout(optionMonth);
        optionMonth.setLayout(optionMonthLayout);
        optionMonthLayout.setHorizontalGroup(
            optionMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionMonthLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(monthLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionMonthLayout.setVerticalGroup(
            optionMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionMonthLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(monthLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        optionCustom.setBackground(new java.awt.Color(240, 240, 240));
        optionCustom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optionCustomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                optionCustomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                optionCustomMouseExited(evt);
            }
        });

        customLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customLabel.setText("Custom");

        javax.swing.GroupLayout optionCustomLayout = new javax.swing.GroupLayout(optionCustom);
        optionCustom.setLayout(optionCustomLayout);
        optionCustomLayout.setHorizontalGroup(
            optionCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionCustomLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(customLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionCustomLayout.setVerticalGroup(
            optionCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionCustomLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(customLabel)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        applyButton.setBackground(new java.awt.Color(40, 75, 135));
        applyButton.setForeground(new java.awt.Color(255, 255, 255));
        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionWeek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(optionCustom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(optionDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionCustom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        todayPanel.setPreferredSize(new java.awt.Dimension(432, 503));

        jLabel3.setText("Date:");

        jLabel17.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel17.setText("Select day");

        dayButton.setText("Set Date");
        dayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout todayPanelLayout = new javax.swing.GroupLayout(todayPanel);
        todayPanel.setLayout(todayPanelLayout);
        todayPanelLayout.setHorizontalGroup(
            todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayPanelLayout.createSequentialGroup()
                .addGroup(todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(todayPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(dayChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(dayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(todayPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        todayPanelLayout.setVerticalGroup(
            todayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todayPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel17)
                .addGap(121, 121, 121)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        mainPanel.add(todayPanel, "card2");

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel5.setText("Select Week");

        jLabel6.setText("Select any day of the week:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date Range:");

        dateRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        setWeekDateButton.setText("Set");
        setWeekDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setWeekDateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout weekPanelLayout = new javax.swing.GroupLayout(weekPanel);
        weekPanel.setLayout(weekPanelLayout);
        weekPanelLayout.setHorizontalGroup(
            weekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weekPanelLayout.createSequentialGroup()
                .addGroup(weekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weekChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(weekPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)
                        .addGap(273, 292, Short.MAX_VALUE))
                    .addGroup(weekPanelLayout.createSequentialGroup()
                        .addGroup(weekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(weekPanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(dateRange, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weekPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setWeekDateButton)
                        .addGap(55, 55, 55)))
                .addContainerGap())
            .addGroup(weekPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        weekPanelLayout.setVerticalGroup(
            weekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weekPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setWeekDateButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateRange)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        mainPanel.add(weekPanel, "card4");

        jLabel10.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel10.setText("Select Month and Year");

        setMonthButton.setText("View Date Range");
        setMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMonthButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jLabel4.setText("Date Range:");

        monthDateRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout monthPanelLayout = new javax.swing.GroupLayout(monthPanel);
        monthPanel.setLayout(monthPanelLayout);
        monthPanelLayout.setHorizontalGroup(
            monthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthPanelLayout.createSequentialGroup()
                .addGroup(monthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monthPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(monthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(monthDateRange, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(monthPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel10))
                    .addGroup(monthPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(monthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, monthPanelLayout.createSequentialGroup()
                                .addComponent(monthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yearChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(setMonthButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        monthPanelLayout.setVerticalGroup(
            monthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addGap(67, 67, 67)
                .addGroup(monthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(setMonthButton)
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(monthDateRange)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        mainPanel.add(monthPanel, "card5");

        jLabel13.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel13.setText("Custom");

        jLabel7.setText("Start Date:");

        jLabel8.setText("End Date:");

        setCustomButton.setText("Set");
        setCustomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCustomButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jLabel9.setText("Date Range:");

        javax.swing.GroupLayout customPanelLayout = new javax.swing.GroupLayout(customPanel);
        customPanel.setLayout(customPanelLayout);
        customPanelLayout.setHorizontalGroup(
            customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanelLayout.createSequentialGroup()
                .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(customPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(endCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(customPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(customPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(setCustomButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customDateRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(customPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customPanelLayout.setVerticalGroup(
            customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(startCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setCustomButton)
                    .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(customDateRange)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(customPanel, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void setDefaultOptions(){
        optionDay.setBackground(new Color(246,246,246));
        optionWeek.setBackground(new Color(246,246,246));
        optionMonth.setBackground(new Color(246,246,246));
        optionCustom.setBackground(new Color(246,246,246));
        
        
        todayLabel.setForeground(Color.BLACK);   
        weekLabel.setForeground(Color.BLACK);
        monthLabel.setForeground(Color.BLACK);
        customLabel.setForeground(Color.BLACK);
        
        op1Clicked = false;
        op3Clicked = false;
        op4Clicked = false;
        op5Clicked = false;
        
        
    }
    
    private LocalDate today = LocalDate.now();
    
    private void setTodayDate(){
        DateFormat dtf = new SimpleDateFormat("yyyy-MM-dd");
        DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String dateInString = dtf2.format(today);
         
        try{
            Date setDate = (Date)dtf.parse(dateInString);
            dayChooser.setDate(setDate);
        }catch(Exception ex){
            System.out.println("Error: " +ex.getMessage());
        }
        
        
      //  Date setToday = dtf.format(today);
  
    }
    
    
    
    
    private void setWeekDate(LocalDate date){
       
        LocalDate startDay = date.with(DayOfWeek.MONDAY);
        LocalDate endDay = date.with(DayOfWeek.SATURDAY);
        DateTimeFormatter dtf2 = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        DateTimeFormatter dtf3 = DateTimeFormatter.ofPattern("MMMM dd, yyyy");
        String startDateInString = dtf2.format(startDay);
        String endDateInString = dtf2.format(endDay);
        String dateRangeText = dtf3.format(startDay) +" - "+ dtf3.format(endDay);
            
        dateRange.setText(dateRangeText);
        
        
        this.startDate = startDateInString;
        this.endDate = endDateInString;
        
    }
    
    private void setMonthDate(LocalDate date){

        YearMonth yearMonth = YearMonth.from(date);
        
        
        LocalDate startDay = yearMonth.atDay(1);
        LocalDate endDay = yearMonth.atEndOfMonth();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String startDateInString = dtf.format(startDay);
        String endDateInString = dtf.format(endDay);
        
        
        DateTimeFormatter forText = DateTimeFormatter.ofPattern("MMMM dd, yyyy");
        
        monthDateRange.setText(forText.format(startDay)+" - "+forText.format(endDay));
        
        this.startDate = startDateInString;
        this.endDate = endDateInString;
    }
    
       
    
    
    private boolean op1Clicked = false, 
                    op3Clicked = false,
                    op4Clicked = false,
                    op5Clicked = false;
    
    
    private void optionDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionDayMouseClicked
        // TODO add your handling code here:
        setDefaultOptions();
        optionDay.setBackground(new Color(40,75,135));
        todayLabel.setForeground(Color.WHITE);
        op1Clicked=true;
        setTodayDate();
        
  
        todayPanel.setVisible(true);
        weekPanel.setVisible(false);
        monthPanel.setVisible(false);
        customPanel.setVisible(false);
    }//GEN-LAST:event_optionDayMouseClicked

    private void optionDayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionDayMouseEntered
        // TODO add your handling code here:
       if(!op1Clicked)
            optionDay.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_optionDayMouseEntered

    private void optionDayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionDayMouseExited
        // TODO add your handling code here:
        if(!op1Clicked)
            optionDay.setBackground(new Color (246,246,246));
    }//GEN-LAST:event_optionDayMouseExited

    private void optionWeekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionWeekMouseClicked
        // TODO add your handling code here:
        setDefaultOptions();
        optionWeek.setBackground(new Color(40,75,135));
        weekLabel.setForeground(Color.WHITE);
        op3Clicked = true;
        setWeekDate(today);
        
        
        
        todayPanel.setVisible(false);
        weekPanel.setVisible(true);
        monthPanel.setVisible(false);
        customPanel.setVisible(false);
    }//GEN-LAST:event_optionWeekMouseClicked

    private void optionWeekMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionWeekMouseEntered
        // TODO add your handling code here:
         if (!op3Clicked)
            optionWeek.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_optionWeekMouseEntered

    private void optionWeekMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionWeekMouseExited
        // TODO add your handling code here:
         if (!op3Clicked)
            optionWeek.setBackground(new Color(246,246,246));
    }//GEN-LAST:event_optionWeekMouseExited

    private void optionMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMonthMouseClicked
        // TODO add your handling code here:
        setDefaultOptions();
        optionMonth.setBackground(new Color(40,75,135));
        monthLabel.setForeground(Color.WHITE);
        op4Clicked = true;
        
        
        
        setMonthDate(today);
        
        todayPanel.setVisible(false);
        weekPanel.setVisible(false);
        monthPanel.setVisible(true);
        customPanel.setVisible(false);
    }//GEN-LAST:event_optionMonthMouseClicked

    private void optionMonthMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMonthMouseEntered
        // TODO add your handling code here:
        if (!op4Clicked)
            optionMonth.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_optionMonthMouseEntered

    private void optionMonthMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionMonthMouseExited
        // TODO add your handling code here:
            if (!op4Clicked)
            optionMonth.setBackground(new Color(246,246,246));
    }//GEN-LAST:event_optionMonthMouseExited

    private void optionCustomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionCustomMouseClicked
        // TODO add your handling code here:
        setDefaultOptions();
        optionCustom.setBackground(new Color(40,75,135));
        customLabel.setForeground(Color.WHITE);
        op5Clicked = true;
        
        
        todayPanel.setVisible(false);
        weekPanel.setVisible(false);
        monthPanel.setVisible(false);
        customPanel.setVisible(true);
    }//GEN-LAST:event_optionCustomMouseClicked

    private void optionCustomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionCustomMouseEntered
        // TODO add your handling code here:
            if (!op5Clicked)
            optionCustom.setBackground(new Color(230,230,230));
    }//GEN-LAST:event_optionCustomMouseEntered

    private void optionCustomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optionCustomMouseExited
        // TODO add your handling code here:
            if (!op5Clicked)
            optionCustom.setBackground(new Color(246,246,246));
    }//GEN-LAST:event_optionCustomMouseExited

    private void setMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMonthButtonActionPerformed
        // TODO add your handling code here:
        
        int month = monthChooser.getMonth();
        int year = yearChooser.getYear();
        
        LocalDate getMonth = LocalDate.of(year, month+1,1);
        setMonthDate(getMonth);
       
        
    }//GEN-LAST:event_setMonthButtonActionPerformed

    private void setWeekDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setWeekDateButtonActionPerformed
        // TODO add your handling code here
        SimpleDateFormat toPass = new SimpleDateFormat("yyyy-MM-dd");
        
        String dateToPass = toPass.format(weekChooser.getDate());
        LocalDate chosenDate = LocalDate.parse(dateToPass);
        
        setWeekDate(chosenDate);
        
    }//GEN-LAST:event_setWeekDateButtonActionPerformed

    private void setCustomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCustomButtonActionPerformed
        // TODO add your handling code here:
       // DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        SimpleDateFormat dtf = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat forText = new SimpleDateFormat("MMMM dd, yyyy");
        
        Date startFromCalendar = startCalendar.getDate();
        Date endFromCalendar = endCalendar.getDate();
        
        
        
        String start = dtf.format(startFromCalendar);
        String end = dtf.format(endFromCalendar);
        
       
        
        if (startFromCalendar.before(endFromCalendar)){
            this.startDate = start;
            this.endDate = end;
            
            customDateRange.setText(forText.format(startFromCalendar) + " - "+forText.format(endFromCalendar));
        }else{
            JOptionPane.showMessageDialog(this, "Please select a start date that occurs before the selected end date", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_setCustomButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        // TODO add your handling code here:

        ActionEvent pressed = new ActionEvent(applyButton, 0, "Nothing");
            
        
        if (op1Clicked){
            dayButtonActionPerformed(pressed);
            this.dispose();
        }else if(op3Clicked){
            setWeekDateButtonActionPerformed(pressed);
            this.dispose();
        }else if (op4Clicked){
            setMonthButtonActionPerformed(pressed);
            this.dispose();
        }else if (op5Clicked){
            setCustomButtonActionPerformed(pressed);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Please select custom date range first!","Error!", JOptionPane.WARNING_MESSAGE);
        }

        
    }//GEN-LAST:event_applyButtonActionPerformed

    private void dayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayButtonActionPerformed
        // TODO add your handling code here:
        
        SimpleDateFormat dtf = new SimpleDateFormat("yyyy-MM-dd");
        
        String date = dtf.format(dayChooser.getDate());
        this.startDate = date;
        this.endDate = date;
    }//GEN-LAST:event_dayButtonActionPerformed

    
    public String getStartDate(){
        return this.startDate;
    }
    
    public String getEndDate(){
        return this.endDate;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dateRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dateRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dateRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dateRange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dateRange dialog = new dateRange(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel customDateRange;
    private javax.swing.JLabel customLabel;
    private javax.swing.JPanel customPanel;
    private com.toedter.calendar.demo.DateChooserPanelBeanInfo dateChooserPanelBeanInfo1;
    private javax.swing.JLabel dateRange;
    private javax.swing.JButton dayButton;
    private com.toedter.calendar.JDateChooser dayChooser;
    private com.toedter.calendar.JCalendar endCalendar;
    private com.toedter.calendar.demo.JCalendarDemo jCalendarDemo1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private com.toedter.calendar.JMonthChooser monthChooser;
    private javax.swing.JLabel monthDateRange;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JPanel monthPanel;
    private javax.swing.JPanel optionCustom;
    private javax.swing.JPanel optionDay;
    private javax.swing.JPanel optionMonth;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel optionWeek;
    private javax.swing.JButton setCustomButton;
    private javax.swing.JButton setMonthButton;
    private javax.swing.JButton setWeekDateButton;
    private com.toedter.calendar.JCalendar startCalendar;
    private javax.swing.JLabel todayLabel;
    private javax.swing.JPanel todayPanel;
    private com.toedter.calendar.JCalendar weekChooser;
    private javax.swing.JLabel weekLabel;
    private javax.swing.JPanel weekPanel;
    private com.toedter.calendar.JYearChooser yearChooser;
    // End of variables declaration//GEN-END:variables
}
